Repository okaryo/remark-link-card-plus, pull requests merged in 2025-07, with the labels that each got.

#49 Update Node.js engine requirement to >=20
  package-lock.json
  package.json
Labels: maintenance

#57 Update example projects
  example/astro.config.mjs
  example/package-lock.json
  example/package.json
  example/src/content/demo/example.md
  example/src/layouts/Layout.astro
  example/src/styles/index.css
  example/src/styles/remark-link-card.css
  example/tailwind.config.mjs
  package-lock.json
  package.json
Labels: documentation

#59 Support SVG favicons with charset in Content-Type
  src/index.test.ts
  src/index.ts
Labels: refinement

#60 Extends ogTransformer with URL parameter
  README.md
  src/index.test.ts
  src/index.ts
Labels: feature
